# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7619020d7d23c2de4d41e33f930f29ca32df7f0ea84c1a488bca360f496795d25a63c03e797b65532f6ee0fa6fcacc433159e7e7647286a33c567271834b3b

test:
  secret_key_base: fe67f19dc67013fe5da85a1b5926d75fb1cc1373b6116a8bcb55c232618c0207ad951b8879c2cc6956d9feb2a480c90a15f2f7e4880794e7e5d53c569eba723f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
